---
- name: Ready all Ubuntu {{ubuntu_releasever}} containers
  with_inventory_hostnames: all:!lxd_servers:!centos_ss
  lxd_container:
    name: "{{item}}"
    state: started
    source:
      type: image
      mode: pull
      server: https://cloud-images.ubuntu.com/releases
      protocol: simplestreams
      alias: "{{ ubuntu_releasever }}"
    profiles: ["default"]
    wait_for_ipv4_addresses: true
    timeout: 600
  tags:
    - ubuntu-container-init

- name: Ready all CentOS {{centos_releasever}} containers
  with_inventory_hostnames: centos_ss
  lxd_container:
    name: "{{item}}"
    state: started
    source:
      type: image
      mode: pull
      server: https://images.linuxcontainers.org
      protocol: lxd
      alias: centos/{{centos_releasever}}/amd64
    profiles: ["default"]
    wait_for_ipv4_addresses: true
    timeout: 600
  tags:
    - centos-container-init

